spring:
  application:
    name: hello-dubbo-service-user-consumer
server:
  port: 9091
user:
  service:
    version: 1.0.0
dubbo:
  scan:
    basePackages: com.hangz.hello.dubbo.service.user.consumer.controller
  application:
    id: hello-dubbo-service-user-consumer
    name: hello-dubbo-service-user-consumer
  registry:
    id: zookeeper
    address: zookeeper://192.168.136.130:2181
    check: false
  consumer:
    check: false


# Enables Dubbo All Endpoints
management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
        ## StatusChecker Name extras (default : empty )
        extras: load,threadpool



